---
title: 'Benford''s Law:  US COVID-19'
author: "David Jackson"
date: "11/22/2020"
output: 
  html_document: 
    fig_width: 9
    fig_height: 7
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(benford.analysis)
library(ggplot2)
library(scales)
theme_set(theme_linedraw() + theme(panel.grid = element_line(linetype = 'dashed')))
options(scipen=999)
```

### Benford's Law Analysis of US COVID-19 Data


```{r}
rm(list=ls())
df <- read.csv("./us_counties.csv")
set.seed(421)
```

#### Generates benford object: Daily Cases First digit

```{r}
X <- cp <- benford(df$new_cases,1,sign="both")
plot(X,multiple=FALSE)

```

#### Generates benford object: Daily Deaths First digit

```{r}
Y <- cp <- benford(df$new_deaths,1,sign="both")
plot(Y,multiple=FALSE)
```

### Benford's Law and New York COVID-19 Data
#### Daily Cases First Digit

```{r}
NY <- subset(df,state=="New York")
```
```{r}
XX <- benford(NY$new_cases,1,sign="both")
plot(XX,multiple=FALSE)
```

#### Daily Deaths First Digit

```{r}
YY<- benford(NY$new_deaths,1,sign="both")
plot(YY,multiple=FALSE)
```


#### DAily Cases First Two Digits

```{r}
XXX <- benford(df$new_cases,2,sign="both")
plot(XXX,multiple=FALSE)
```

#### Daily Deaths First Two Digits

```{r}
YYY <- benford(df$new_deaths,2,sign="both")
plot(YYY,multiple=FALSE)
```