---
title: "The World COVID-19 Benfords Law"
author: "David Jackson"
date: "11/25/2020"
output: 
  html_document: 
    fig_width: 9
    fig_height: 7
---

```{r setup,echo=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE,message = FALSE)
library(benford.analysis)
library(RSQLite)
library(ggplot2)
library(scales)
library(dplyr)

```

### Benford's Law with  benford.analysis Package

```{r}
rm(list=ls())
db <- db <- dbConnect(RSQLite::SQLite(),dbname= "../COVIDDB/COVID.sqlite3")
df <- dbGetQuery(db,"select geoID,Cases,Deaths from ECDC")
df <- subset(df,geoID=="CN")
dbDisconnect(db)
```

#### Generates benford object First Digit: Daily Cases

```{r}
X  <- benford(df$Cases,1,sign="both")
plot(X,multiple=FALSE)
```

### First Two Digit : Daily Cases

```{r}
X  <- benford(df$Cases,2,sign="both")
plot(X,multiple=FALSE)
```

#### Generates benford object First Digit: Daily Deaths

```{r}
Y  <- benford(df$Deaths,1,sign="both")
plot(Y,multiple=FALSE)

```

#### First Two Digits: Deaths


```{r}
Y  <- benford(df$Deaths,2,sign="both")
plot(Y,multiple=FALSE)

```

#### Percentages for First Digit Cases and Deaths

```{r}
bfd_cases <- X$bfd
ggplot(bfd_cases) + geom_col(aes(x=digits,y=data.dist,col="Actual")) +
geom_line(aes(x=digits,y=benford.dist,col="Benford")) +
  labs(title="Bonford's Analysis: Actual vs Benfords Percents") +
  scale_y_continuous(labels = percent)
```

```{r}
bfd_deaths <- Y$bfd
ggplot(bfd_deaths) + geom_col(aes(x=digits,y=data.dist,col="Actual")) +
geom_line(aes(x=digits,y=benford.dist,col="Benford")) +
  labs(title="Bonford's Analysis: Actual vs Benfords Percents") +
  scale_y_continuous(labels = percent)
```